name: qa plan and apply

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  id-token: write
  contents: read

jobs:
  qa-plan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: terraform_commons
        uses: ./.github/actions/terraform_commons
        with:
          action: "plan"
          env_name: "env_qa"

      - name: Upload tfplan
        working-directory: ${{ github.workspace }}/env_qa
        uses: actions/upload-artifact@v4
        with:
          name: qa-tfplan
          path: env_qa/tfplan

  qa-apply:
    needs: qa-plan
    runs-on: ubuntu-latest
    environment: qa
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}

    steps:
      - uses: actions/checkout@v4

      - name: change directory
        run: cd env_qa
        shell: bash

      - name: Download tfplan
        uses: actions/download-artifact@v4
        with:
          name: qa-tfplan
          path: env_qa

      - name: Debug show downloaded files
        run: ls -la

      - name: Terraform Apply
        uses: ./.github/actions/terraform_commons
        with:
          action: "apply"
          env_name: "env_qa"
          
